.NET Framework Projects/MVC Projects/Blogger/BloggerWeb/Controllers/BlogsController.cs
using BloggerWeb.Models.ViewModals;
using BloggerWeb.Repositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using BloggerWeb.Models.Domain;

namespace BloggerWeb.Controllers
{
    public class BlogsController : Controller
    {
        private readonly IBlogPostRepository blogRepository;
        private readonly IBlogPostLikeRepository blogPostLikeRepository;
        private readonly SignInManager<IdentityUser> signInManager;
        private readonly UserManager<IdentityUser> userManager;
        private readonly IBlogPostCommentRepository blogPostCommentRepository;

        public BlogsController(IBlogPostRepository blogRepository, IBlogPostLikeRepository blogPostLikeRepository,
            SignInManager<IdentityUser> signInManager,
            UserManager<IdentityUser> userManager,
            IBlogPostCommentRepository blogPostCommentRepository)
        {
            this.blogRepository = blogRepository;
            this.blogPostLikeRepository = blogPostLikeRepository;
            this.signInManager = signInManager;
            this.userManager = userManager;
            this.blogPostCommentRepository = blogPostCommentRepository;
        }

        [HttpGet]
        public async Task< IActionResult> Index(string urlHandle)
        {
            var liked = false;
            var blogPost = await blogRepository.GetByUrlHanldeAsync(urlHandle);
            var blogDetailsViewModel = new BlogDetailsViewModel();
    
            if (blogPost != null)             
            {

                var totalLikes = await blogPostLikeRepository.GetTotalLikes(blogPost.Id);

                if (signInManager.IsSignedIn(User)) {

                    var likesForBlog = await blogPostLikeRepository.GetLikesForBlog(blogPost.Id);

                    var userId = userManager.GetUserId(User);

                    if (userId != null)
                    {

                       var likeFromUser = likesForBlog.FirstOrDefault(x => x.UserId == Guid.Parse(userId));
                        liked = likeFromUser != null;
                        
                    }

                }

                blogDetailsViewModel = new BlogDetailsViewModel
                {
                    Id = blogPost.Id,
                    Content = blogPost.Content,
                    PageTitle = blogPost.PageTitle,
                    Author = blogPost.Author,
                    FeaturedImageUrl = blogPost.FeaturedImageUrl,
                    Heading = blogPost.Heading,
                    PublishedDate = blogPost.PublishedDate,
                    ShortDescription = blogPost.ShortDescription,
                    UrlHandle = blogPost.UrlHandle,
                    Visible = blogPost.Visible,
                    Tags = blogPost.Tags,
                    TotalLikes = totalLikes,
                    Liked = liked
                };

            }

            return View(blogDetailsViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Index(BlogDetailsViewModel blogDetailsViewModel) {

            if (signInManager.IsSignedIn(User)) 
            {
                var domainModel = new BlogPostComment
                {
                    BlogPostId = blogDetailsViewModel.Id,
                    Description = blogDetailsViewModel.CommentsDescription,
                    UserId = Guid.Parse(userManager.GetUserId(User)),
                    DateAdded = DateTime.Now
                };

                await blogPostCommentRepository.AddAsync(domainModel);
                return RedirectToAction("Index", "Home", new {
                    urlHandle = blogDetailsViewModel.UrlHandle,
                });
            }

            return View();
        

        }

    }
}

.NET Framework Projects/MVC Projects/Blogger/BloggerWeb/Controllers/HomeController.cs
using BloggerWeb.Models;
using BloggerWeb.Models.Domain;
using BloggerWeb.Models.ViewModals;
using BloggerWeb.Repositories;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace BloggerWeb.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IBlogPostRepository blogPostRepository;
        private readonly ITagRepository tagRepository;

        public HomeController(ILogger<HomeController> logger, IBlogPostRepository blogPostRepository, ITagRepository tagRepository)
        {
            _logger = logger;
            this.blogPostRepository = blogPostRepository;
            this.tagRepository = tagRepository;
        }

        public async Task<IActionResult> Index()
        {   
            //getting all blogs 
            var blogPosts = await blogPostRepository.GetAllAsync();

            //get all tags
            var tags = await tagRepository.GetAllAsync();

            var model = new HomeViewModelcs
            {
                BlogPosts = blogPosts,
                Tags = tags
            };
            return View(model);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

.NET Framework Projects/MVC Projects/Blogger/BloggerWeb/Views/Home/Index.cshtml
@model BloggerWeb.Models.ViewModals.HomeViewModelcs
@{
    ViewData["Title"] = "Home Page";
}

<div class="container col-xxl-8 px-4 py-5">

    <div class="row align-items-center g-5 py-5">
        <div class="col-12 col-lg-6">
             <h1 class="display-5 fw-bold lh-1 mb-3">Blogger - The Dev Blog</h1>
             <p class="lead">Blogger is the home of coding blogs covering vast range of topics like HTML, CSS, JavaScript, ASP.NET, C#, Angular, etc.
                 Want to read the lastest dev article? Join the blogger app and get ready blogs in your email.
             </p>
        </div>

        <div class="col-12 col-lg-6">
            <img src="https://images.pexels.com/photos/1181449/pexels-photo-1181449.jpeg" alt="Blogger Dev Blogs" class="d-block mx-lg-auto img-fluid" width="300" />

        </div>
    </div>

</div>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-6 d-flex">
            @if (Model != null && Model.Tags.Any())
            {
                foreach (var tag in Model.Tags)
                {
                    <span class="badge bg-dark">
                        @tag.Name
                    </span>
                
                }

            }
        </div>
    </div>
  
</div>


<div class="container">
    <div class="row justify-content-center align-items-center">
         <div class="col-6">
            @if (@Model != null && Model.BlogPosts.Any())
            {
                foreach (var blogPost in Model.BlogPosts)
                {   
                    <div class="mb-5 bg-light box-shadow p-2">
                        <img src="@blogPost.FeaturedImageUrl" alt="@blogPost.Heading" class="mb-2 d-block img-fluid" />
                        <h2 class="mb-4">@blogPost.Heading</h2>
                        <p class="mb-4">
                            Author: @blogPost.Author
                            <br/>
                            Published Date: @blogPost.PublishedDate.ToShortDateString();
                        </p>

                        <p class="mb-4">
                            @foreach (var tag in blogPost.Tags)
                            {
                                <span class="badge bg-secondary me-1">@tag.Name</span>

                            }
                        </p>

                        <p class="mb-4">
                            @blogPost.ShortDescription
                        </p>

                        <a class="btn btn-dark" asp-area="" asp-controller="Blogs" asp-action="Index" asp-route-urlHandle="@blogPost.UrlHandle">Read More</a>
                     </div>
                }
            }
        </div>
    </div>
</div>